version: '3.3'
services:
  db:
    container_name: db
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    ports:
      - "33006:3306"
    expose:
      - '33006'
    volumes:
      - ./db_test_casbin:/var/lib/mysql
volumes:
  db_test_casbin:
